#!/bin/bash

# Author: Erik Vargas
# This script enables the root account, allows SSH login as root, and sets the root password to 'root' (insecure).

Log into your VM with SSH and enable the root account and allow SSH login with root
sudo grep -q '^PermitRootLogin' /etc/ssh/sshd_config && sudo sed -i 's/^PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config || echo 'PermitRootLogin yes' | sudo tee -a /etc/ssh/sshd_config && sudo systemctl restart sshd

Log into your VM with SSH and set the root password to “root” (Insecure OS configuration):
sudo passwd root
